# Generated by Django 5.1.2 on 2025-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organisation_appuser_is_oneline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
