# Generated by Django 5.1.2 on 2025-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
