# Generated by Django 5.1.2 on 2025-05-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_populate_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
