# Generated by Django 5.1.2 on 2025-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_sample_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='required_complete',
            field=models.BooleanField(default=False),
        ),
    ]
